# Generated by Django 4.2.4 on 2023-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vehile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_no', models.CharField(max_length=8)),
                ('Vehicle_type', models.CharField(max_length=20)),
                ('Vehicle_model', models.CharField(max_length=30)),
                ('Vehicle_des', models.TextField()),
            ],
        ),
    ]
